"""empty message

Revision ID: a4b9ba7f3140
Revises: 21f4cde31804
Create Date: 2024-05-31 16:33:42.386887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b9ba7f3140'
down_revision = '21f4cde31804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('sitters', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sitters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
